version: '3.8'
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work
  web:
    ports:
      - 80:80
    # volumes:
    #   - ./backend:/work
    #   - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    build: ./infra/nginx
    volumes:
      - ./backend:/work
    working_dir: /work
    networks:
      - default
      - shared-network
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports: ['8890:80']
    depends_on: ['db']
volumes:
  db-store:

networks:
  shared-network:
    external: true
